FROM node:24-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build


FROM caddy:2-alpine AS production

WORKDIR /srv

COPY Caddyfile /etc/caddy/Caddyfile

COPY --from=build /app/dist /srv

EXPOSE 80 443