INSERT INTO "categories" (
  "id",
  "slug",
  "name_ru",
  "name_en",
  "image_path",
  "sort_order",
  "is_published",
  "created_at",
  "updated_at"
)
VALUES
  (
    gen_random_uuid(),
    'tables',
    'Столы',
    'Tables',
    NULL,
    10,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'lighting',
    'Освещение',
    'Lighting',
    NULL,
    20,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'seating',
    'Мягкая мебель',
    'Seating',
    NULL,
    30,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'storages',
    'Системы хранения',
    'Storages',
    NULL,
    40,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'consoles',
    'Консоли',
    'Consoles',
    NULL,
    50,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'mirrors',
    'Зеркала',
    'Mirrors',
    NULL,
    60,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("slug") DO NOTHING;